apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 18.0.0
    helm:
      releaseName: prometheus
      parameters:
      - name: server.ingress.enabled
        value: "true"
      - name: server.ingress.hosts[0]
        value: prometheus.monitoring.zxyxyhome.duckdns.org
      - name: server.persistentVolume.enabled
        value: "true"
      - name: server.persistentVolume.storageClass
        value: prometheus
      - name: server.persistentVolume.volumeName
        value: prometheus
      - name: server.persistentVolume.size
        value: "300Gi"
      - name: server.persistentVolume.accessModes[0]
        value: ReadWriteMany
      - name: extraScrapeConfigs
        value: |
          - job_name: 'freya_monitor'
            scrape_interval: 1m
            scrape_timeout: 30s
            static_configs:
              - targets:
                - 172.21.0.2:9100
          - job_name: 'argocd'
            scrape_interval: 1m
            scrape_timeout: 30s
            static_configs:
              - targets:
                - argo-cd-argocd-server-metrics.argocd.svc.cluster.local:8083
                - argo-cd-argocd-application-controller-metrics.argocd.svc.cluster.local:8082
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
